DFE-Digital/social-work-induction-programme-digital-service

.github/actions/check-endpoint-content/action.yml
.github/workflows/deploy-app-service.yml
.github/workflows/deploy-auth-service.yml
.github/workflows/deploy-moodle-app.yml
.github/workflows/deploy-proxy-service.yml
.github/workflows/terraform.yaml
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.AuthorizeAccess/Controllers/KeysController.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.AuthorizeAccess/Infrastructure/Configuration/FeatureFlags.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.AuthorizeAccess/Infrastructure/Security/CertificateExtensions.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.AuthorizeAccess/Infrastructure/Security/Configuration/OneLoginConfiguration.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.AuthorizeAccess/Program.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.AuthorizeAccess/appsettings.Azure.json
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.AuthorizeAccess/appsettings.Development.json
apps/moodle-docker/config.php
terraform/auth-service.tf
terraform/envs/d01/env.tfvars
terraform/envs/d02/env.tfvars
terraform/modules/web-app/front-door-routes.tf
terraform/modules/web-app/web-app.tf
terraform/proxy-service.tf
terraform/variables.tf

- Deployment workflows are now parameterised to accept image version tag to deploy
- OneLogin integration environment is set up for d01 (https://admin.sign-in.service.gov.uk/)
- FrontDoor integration re-enabled - apps now use the Front Door generated URLs
- Implemented JWKS endpoint for auth service (/api/keys/onelogin) to aupport autonomous and automatic key refresh with 24 hour overlap between previous and new key (both supported at same time within window)
- Deployed and serves in Azure, but OneLogin needs end to end testing
Next steps: Moodle / Onelogin integration and front-end deployment

SWIP-311 OneLogin integration for auth service

---

apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/ConfirmAccountDetailsPageTests.cs
apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilityInformationPageTests.cs
apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/SelectAccountTypePageTests.cs
apps/user-management/apps/frontend/Dfe.Sww.Ecf.Frontend.csproj
apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityInformation.cshtml
apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityInformation.cshtml.cs
apps/user-management/apps/frontend/Pages/ManageAccounts/SelectAccountType.cshtml
apps/user-management/apps/frontend/Pages/ManageAccounts/SelectAccountType.cshtml.cs
apps/user-management/apps/frontend/Routing/EcfLinkGenerator.cs
apps/user-management/apps/frontend/Validation/SelectAccountTypeValidator.cs

- Error message and radio options text updated:
- Adds new Eligibility information page and links to it when selecting to add a new ECSW:
- Continue button currently links to AddAccountDetails until SWIP-577 is done
- Bumps GovUk.Frontend.AspNetCore to 2.8.1
- Adds missing unit tests for SelectAccountType page
- Fixed unit test that was broken due to SWIP-335 changes

SWIP-576 - add user content changes and eligibility info page

---

apps/auth-service/Dfe.Sww.Ecf/entry-point.sh
apps/moodle-apps-azure/entry-point.sh
apps/moodle-apps-azure/maintain-moodle.sh
apps/moodle-ddev/.ddev/commands/web/install-oidc-plugin
apps/moodle-docker/config.php
apps/user-management/apps/frontend/Configuration/FeatureFlags.cs
apps/user-management/apps/frontend/Dockerfile-azure
apps/user-management/apps/frontend/Pages/Debug/DebugBasePageModel.cs
apps/user-management/apps/frontend/Program.cs
apps/user-management/apps/frontend/Routing/EcfLinkGenerator.cs
apps/user-management/apps/frontend/appsettings.Azure.json
apps/user-management/apps/frontend/appsettings.Development.json
apps/user-management/apps/frontend/entry-point.sh
terraform/auth-service.tf
terraform/envs/d01/env.tfvars
terraform/envs/d02/env.tfvars
terraform/moodle-web-apps.tf
terraform/user-management.tf

- Enabled web service during deployment
- Enabled Kudu / SSH for user management / auth service
- Provides Moodle app setting MOODLE_SWITCH_OFF_OAUTH to allow OAuth to be toggled on and off for an environment
- Refactored IsDevelopment() checks to feature flags for user management
- Add user management redirects for auth service

SWIP-584 Integrate Moodle web service setup with build and deployment workflows

---

apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.Core/DataStore/Postgres/Models/PersonStatus.cs
apps/user-management/apps/frontend.Test/UnitTests/TagHelpers/AccountStatusTagHelperTests.cs
apps/user-management/apps/frontend/Models/AccountStatus.cs
apps/user-management/apps/frontend/Pages/ManageAccounts/Index.cshtml
apps/user-management/apps/frontend/Pages/ManageAccounts/ViewAccountDetails.cshtml
apps/user-management/apps/frontend/TagHelpers/AccountStatusTagHelper.cs

- Adds the current user status to the view details page:
- Updates the status colours to match what is currently in the prototype:
- Deletes the no-longer used `Paused` status from the auth service
- Adds the `Inactive` status back to the frontend to ensure parity with the prototype

SWIP-650 - View user details status label

---

apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.Core/Services/Accounts/AccountsService.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.Core/Services/Accounts/PersonDto.cs
apps/user-management/apps/frontend.Test/UnitTests/Helpers/Builders/AccountBuilder.cs
apps/user-management/apps/frontend.Test/UnitTests/Helpers/Fakers/PersonFaker.cs
apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/ViewAccountDetailsPageTests.cs
apps/user-management/apps/frontend/HttpClients/AuthService/Models/Person.cs
apps/user-management/apps/frontend/Mappers/AccountMapper.cs
apps/user-management/apps/frontend/Models/Account.cs
apps/user-management/apps/frontend/Models/RegisterSocialWorker/RegisterSocialWorkerJourneyModel.cs
apps/user-management/apps/frontend/Pages/ManageAccounts/ViewAccountDetails.cshtml
apps/user-management/apps/frontend/Pages/ManageAccounts/ViewAccountDetails.cshtml.cs
apps/user-management/apps/frontend/Services/Journeys/CreateAccountJourneyService.cs
apps/user-management/apps/frontend/Services/Journeys/Interfaces/ICreateAccountJourneyService.cs
apps/user-management/apps/frontend/Services/Journeys/RegisterSocialWorkerJourneyService.cs
apps/user-management/apps/frontend/appsettings.Development.json

PR for [SWIP-629](https://dfedigital.atlassian.net.mcas.ms/browse/SWIP-629) including:
- changes to the auth service to return a true/false flag with the details of a given person; this captures whether they have ever logged into our service via OneLogin
- frontend chages to use this "has ever logged in" flag to display the "Resend invitation email" button on the view user details page, only for user that have never logged in
- supressing this button from being displayed for users that have the status "Inactive"
- as part of the ECSW registration journey completion, set the user's status to "Active"
- unit tests
[SWIP-629]: https://dfedigital.atlassian.net/browse/SWIP-629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SWIP-629 Resend registration invite

---

apps/user-management/apps/frontend/Program.cs

Changes to settings for govuk frontend .NET package to inject the error summary at the top of forms instead of the default, which is at the top of main. More info on the decision in [SWIP-660](https://dfedigital.atlassian.net.mcas.ms/browse/SWIP-660).
[SWIP-660]: https://dfedigital.atlassian.net/browse/SWIP-660?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SWIP-660 Set error summary to prepend to form

---

apps/user-management/apps/frontend.Test/UnitTests/Helpers/Builders/AccountBuilder.cs
apps/user-management/apps/frontend.Test/UnitTests/Helpers/Fakers/AccountDetailsFaker.cs
apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/AddAccountDetailsPageTests.cs
apps/user-management/apps/frontend.Test/UnitTests/Validators/AccountDetailsValidatorTests.cs
apps/user-management/apps/frontend/Models/AccountDetails.cs
apps/user-management/apps/frontend/Pages/ManageAccounts/AddAccountDetails.cshtml
apps/user-management/apps/frontend/Pages/ManageAccounts/AddAccountDetails.cshtml.cs
apps/user-management/apps/frontend/Validation/AccountDetailsValidator.cs

Changes as part of [SWIP-653](https://dfedigital.atlassian.net.mcas.ms/browse/SWIP-653):
- logic changes to include the SWE number field when capturing the details of a new assessor
- unit test changes
- validator logic changes
[SWIP-653]: https://dfedigital.atlassian.net/browse/SWIP-653?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SWIP-653 Add SWE number field for assessor details capture

---

.github/workflows/build-and-optionally-deploy-auth-service.yml
.github/workflows/build-and-optionally-deploy-moodle-apps.yml
.github/workflows/build-and-optionally-deploy-notification-api.yml
.github/workflows/build-and-optionally-deploy-proxy-service.yml
.github/workflows/build-and-optionally-deploy-user-management.yml
.github/workflows/build-and-publish-image.yml
apps/auth-service/justfile
apps/moodle-apps-azure/justfile
apps/proxy-app-azure/justfile
apps/user-management/apps/frontend/justfile
apps/user-management/apps/notification-service/justfile
docs/devops/System Runbook.md

- Changed just files to use ci- before build workflow-specific commands (e.g. ci-build, ci-restore), in case CI needs to do something different to normal build, restore
- Added support for testing into build process
- Execution of user management unit tests
- Automatic execution of build process on PR for: Moodle, proxy service, user management, notifications API
- Reformatted runbook for flexibility and adding 'how to' on downgrading Moodle version
- Even though the build process runs tests, the test execution isn't hooked up for auth service / notification API yet, as these tests are failing

SWIP-782 User management, notification API, proxy service and Moodle unit tests 

---

.github/workflows/build-and-optionally-deploy-moodle-apps.yml
.github/workflows/deploy-moodle-app.yml
apps/moodle-apps-azure/Dockerfile
apps/moodle-apps-azure/apache-config-cron.conf
apps/moodle-apps-azure/entry-point.sh

- index.html and version.txt were no longer being served (permission denied)
- Made Moodle cron service dependent on main Moodle site so initial deployments are fully installed before the cron service is deployed

SWIP 907 Moodle cron service fix

---

apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EditAccountDetailsPageTests.cs
apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/SelectUseCasePageTests.cs
apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/EditAccountJourneyServiceTests/GetAccountTypesShould.cs
apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/EditAccountJourneyServiceTests/SetAccountTypesShould.cs
apps/user-management/apps/frontend/Models/EditAccountJourneyModel.cs
apps/user-management/apps/frontend/Pages/ManageAccounts/EditAccountDetails.cshtml
apps/user-management/apps/frontend/Pages/ManageAccounts/EditAccountDetails.cshtml.cs
apps/user-management/apps/frontend/Pages/ManageAccounts/SelectUseCase.cshtml
apps/user-management/apps/frontend/Pages/ManageAccounts/SelectUseCase.cshtml.cs
apps/user-management/apps/frontend/Services/Journeys/EditAccountJourneyService.cs
apps/user-management/apps/frontend/Services/Journeys/Interfaces/IEditAccountJourneyService.cs

Changes for [SWIP-818](https://dfedigital.atlassian.net/browse/SWIP-818) including:
- logic to clear the SWE number when changing existing user account type from Assessor to Coordinator
- logic to capture the SWE number when account type change includes Assessor
- appropriate redirects for the logic above
- edit account details form changes to align with add account details
- storing account details in session as early as possible to avoid unnecessary database calls
- unit tests
[SWIP-818]: https://dfedigital.atlassian.net/browse/SWIP-818?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SWIP-818 change existing staff account type

---

.github/workflows/terraform.yaml
terraform/modules/environment-stack/network.tf
terraform/modules/function-app/function-app.tf
terraform/modules/function-app/network-integration.tf
terraform/modules/function-app/outputs.tf
terraform/modules/function-app/variables.tf
terraform/notification-service.tf
terraform/user-management.tf
terraform/variables.tf

- Adds networking configuration to enable secure communication between user management and the notification service.
- Correctly passes the function app URL to user management
- Passes the function key to user management (future PR to utilise this key in requests)
- Passes the GovNotify API key from the github secrets vault through to Azure KeyVault to be utilised by the notification service.

SWIP-939 - Setup notifications service and networking

---

apps/moodle-ddev/.ddev/commands/web/install-oidc-plugin

Change to ddev command which is used to configure authentication plugin to also include the additional setting for allowing special characters in usernames. This means that we can leverage this setting to support emails like test+1@test.com (emails are used as usernames when adding users to Moodle via web service calls from the user management app).
Change as part of [SWIP-819](https://dfedigital.atlassian.net.mcas.ms/browse/SWIP-819).
[SWIP-819]: https://dfedigital.atlassian.net/browse/SWIP-819?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SWIP-819 Allow extended characters in Moodle usernames

---

apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.AuthorizeAccess/Infrastructure/Configuration/ServicesExtensions.cs
apps/user-management/apps/frontend.Test/UnitTests/HttpClient/AuthServiceClientTests/AccountsOperationsTests.cs
apps/user-management/apps/frontend.Test/UnitTests/HttpClient/AuthServiceClientTests/OrganisationsOperationsTests.cs
apps/user-management/apps/frontend/Filters/UnauthorizedExceptionFilter.cs
apps/user-management/apps/frontend/HttpClients/AuthService/Operations/AccountsOperations.cs
apps/user-management/apps/frontend/HttpClients/AuthService/Operations/BaseOperations.cs
apps/user-management/apps/frontend/HttpClients/AuthService/Operations/OrganisationOperations.cs
apps/user-management/apps/frontend/Installers/InstallAuthentication.cs
apps/user-management/apps/frontend/Program.cs
apps/user-management/apps/frontend/appsettings.Development.json

Change to fix errors captured in [SWIP-826](https://dfedigital.atlassian.net.mcas.ms/browse/SWIP-826) by better management of session expiry:
- auth service changes for access token to expire after 4 hours (absolute timeout)
- frontend changes to api calls for account operations and organisation operations to handle 401 response from the auth service (which would happen after the 4 hours pass) and throw a http response error
- exception filter to trigger the authentication challenge which results in a redirect to the signin page
- absolute session timeout handling for the frontend for standard page requests (not api calls)
- frontend idle session timeout set to 60 minutes so the user has to reauthenticate after 60 minutes of inactivity
- unit test updates
[SWIP-826]: …

SWIP-826 manage session expiry

---

apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.AuthorizeAccess/Infrastructure/Security/ClaimsBuilder.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.AuthorizeAccess/appsettings.Development.json
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.Core/DataStore/Postgres/DatabaseSeeder.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.Core/DataStore/Postgres/DbContextOptionsBuilderExtensions.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.Core/Infrastructure/Configuration/DatabaseSeedOptions.cs
apps/auth-service/tools/onelogin-simulator/compose.yml
terraform/envs/d01/env.tfvars
terraform/envs/d02/env.tfvars
terraform/envs/d03/env.tfvars

- Seeds the initial user with the admin role
- Removes config to seed initial org as it's no longer needed, but kept the code as optional for potential future use in automated tests
- Fixes an issues where setting the orgId claim was throwing an exception when the user wasn't part of an org (like an admin user)

SWIP-941 - Seed initial user as admin

---

.github/workflows/checkov.yml
.github/workflows/db-backup-restore.yml
terraform/db-jobs-app.tf
terraform/modules/function-app/function-app.tf
terraform/modules/function-app/variables.tf

- Adds the ability to create a function app with public access enabled and also the option to ensure that access is restricted to requests that come via front door
- For security, public access can only be enabled if front door restrictions are in place
- Enabled this for the new db-jobs-app

SWIP-684 - Allow access to db-jobs-app via front door

---

apps/moodle-ddev/plugins/theme/govuk_swpdp/config.php
apps/moodle-ddev/plugins/theme/govuk_swpdp/lib.php
apps/moodle-ddev/plugins/theme/govuk_swpdp/version.php

Change for the Moodle child theme `govuk swpdp` to load the styles from the govuk theme as part of its css post process. We ensure we don't include the styles twice by excluding the sheet from being loaded as part of the parent. The issue this fixes relates to boost styles loading after the govuk theme styles in the child theme, which means we're seeing styles overrides not being applied.
As part of [SWIP-1043](https://dfedigital.atlassian.net.mcas.ms/browse/SWIP-1043) where the child theme was created.
[SWIP-1043]: https://dfedigital.atlassian.net/browse/SWIP-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SWIP-1043 Load govuk styles as child theme css post process

---

.github/actions/sync-key-vault-secrets/action.yml

Fix for code scanning alerts of "medium" priority linked to code injection. Implemented the recommendation made in the alert to pass inputs as environment variables into the bash script.
Sync key vault secrets action is not currently referenced in workflows from what I could see.
[Code injection alert #15](https://github.com/DFE-Digital/social-work-induction-programme-digital-service/security/code-scanning/15)
[Code injection alert #16](https://github.com/DFE-Digital/social-work-induction-programme-digital-service/security/code-scanning/16)
[Code injection alert #17](https://github.com/DFE-Digital/social-work-induction-programme-digital-service/security/code-scanning/17)

SWIP-953 Resolve code injection alerts

---

apps/moodle-ddev/plugins/theme/customlang_en/data.php
apps/moodle-ddev/plugins/theme/govuk_swpdp/classes/helpers/common_helpers.php
apps/moodle-ddev/plugins/theme/govuk_swpdp/classes/hooks/primary_nav.php
apps/moodle-ddev/plugins/theme/govuk_swpdp/config.php
apps/moodle-ddev/plugins/theme/govuk_swpdp/lib.php
apps/moodle-ddev/plugins/theme/govuk_swpdp/renderers.php
apps/moodle-ddev/plugins/theme/govuk_swpdp/scss/govuk_swpdp.scss
apps/moodle-ddev/plugins/theme/govuk_swpdp/style/govuk_swpdp.css
apps/moodle-ddev/plugins/theme/govuk_swpdp/templates/mod_data/view_noentries.mustache
apps/moodle-ddev/plugins/theme/govuk_swpdp/version.php

Changes as part of [SWIP-1109](https://dfedigital.atlassian.net.mcas.ms/browse/SWIP-1109):
- empty h1 to remove the organisation name from the view database pages (both empty page and page with entries given the moodle template is common and this is as per Lucid designs); 
Also included styling override to ensure no empty space for the h1, and styled the heading which we want to display, the h2, as a large heading in this scenario. Future work needed to decide how we handle headings [SWIP-1169: Discuss and explore solution for page heading handling on database activities](https://dfedigital.atlassian.net.mcas.ms/browse/SWIP-1169)
- removal of group select option for ECSW (non staff users in the logic itself) and styling override to ensure no empty space on the page when this is done
- …

SWIP-1109 format empty db activity page

---

apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.AuthorizeAccess/appsettings.Development.json
terraform/envs/d01/env.tfvars

Disabling the auth service's generic `/error` page on d01 and for local dev to help expose errors/exceptions occurring

SWIP-1180: ops(debug): disable auth service generic error page on d01 and local

---

apps/user-management/apps/frontend/Pages/Shared/_Layout.cshtml

SWIP-1116 - fix: Change user management phase banner to 'beta'

---

apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.Core/DataStore/Postgres/Mappings/PersonMapping.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.Core/DataStore/Postgres/Migrations/20251007110740_SyncPersonsTable.Designer.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.Core/DataStore/Postgres/Migrations/20251007110740_SyncPersonsTable.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.Core/DataStore/Postgres/Migrations/20251007111150_ExtendPersonsEmailColumnLength.Designer.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.Core/DataStore/Postgres/Migrations/20251007111150_ExtendPersonsEmailColumnLength.cs
apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.Core/DataStore/Postgres/Models/Person.cs

For SWIP-949:
- Updated Person model [MaxLength] attribute to 254 to align with [RFC 3696 Errata 1690](https://www.rfc-editor.org/errata/eid1690)
- Tested with an email that's exactly 254 characters: `long.email.address.testing.maximum.length.limit.abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz@subdomain1.subdomain2.subdomain3.reallylongdomainnamefortestingpurposes.thisisstillgoing.verylongdomainnameindeed.example.co.uk`
I also did the following:
- Added data annotations to Person model for key, required, and max length constraints to match DB
- Introduced DatabaseGenerated attributes for PersonId and CreatedOn
- Updated PersonMapping to set gen_random_uuid() default for PersonId to match DB
- Removed duplicate OtherGenderIdentity mapping
- Synced EF Core …

SWIP-949 - feat(data): extend PersonEmailAddress max length
