- apps/user-management/apps/frontend/appsettings.Azure.json
- terraform/modules/web-app/outputs.tf
- terraform/user-management.tf
Basic Terraform provisioning for user management - adds the web app to the services app plan (same plan as auth service)
> SWIP-457 Basic Terraform provisioning for user management

- .github/workflows/build-and-optionally-deploy-user-management.yml
- apps/user-management/apps/frontend/Dockerfile-azure
- apps/user-management/apps/frontend/appsettings.Azure.json
- apps/user-management/apps/frontend/justfile
- apps/user-management/apps/frontend/sshd_config
- terraform/user-management.tf
Adds build / optional deploy workflow for user management. User management is shown in Azure, but end to end testing with Onelogin remains to be fully configured and tested.
> SWIP-458 Workflow for user management combined build / deploy

- .github/workflows/build-and-optionally-deploy-moodle-apps.yml
- apps/moodle-apps-azure/Dockerfile
- apps/moodle-ddev/.ddev/commands/web/install-theme
Parameterizing the Gov UK theme version from a github repo level variable MOODLE_GOV_UK_THEME_VERSION
> SWIP-439 Parameterizing the Gov UK theme version from a github repo level variable

- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilitySocialWorkEnglandPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/CreateAccountJourneyServiceTests/GetIsRegisteredWithSocialWorkEnglandShould.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/CreateAccountJourneyServiceTests/SetIsRegisteredWithSocialWorkEnglandShould.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilitySocialWorkEngland.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilitySocialWorkEnglandDropout.cshtml
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilitySocialWorkEnglandDropout.cshtml.cs
- apps/user-management/apps/frontend/Routing/EcfLinkGenerator.cs
- apps/user-management/apps/frontend/Services/Journeys/CreateAccountJourneyService.cs
- apps/user-management/apps/frontend/Services/Journeys/Interfaces/ICreateAccountJourneyService.cs
- Adds eligibility SWE dropout page when selecting "no" on previous eligibility SWE question page
> SWIP-590 - Eligibility SWE dropout page

- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilitySocialWorkEnglandPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilityStatutoryWorkPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/CreateAccountJourneyServiceTests/GetIsStatutoryWorkerShould.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/CreateAccountJourneyServiceTests/SetIsStatutoryWorkerShould.cs
- apps/user-management/apps/frontend/Models/CreateAccountJourneyModel.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityStatutoryWork.cshtml
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityStatutoryWork.cshtml.cs
- apps/user-management/apps/frontend/Routing/EcfLinkGenerator.cs
- apps/user-management/apps/frontend/Services/Journeys/CreateAccountJourneyService.cs
- apps/user-management/apps/frontend/Services/Journeys/Interfaces/ICreateAccountJourneyService.cs
- apps/user-management/apps/frontend/Validation/EligibilityStatutoryWorkValidator.cs
- Adds eligibility statutory work question page after user answers "yes" to previous eligibility SWE question with error state for null answer
> SWIP-579 - Add eligibility statutory work question page

- .github/workflows/deploy-app-service.yml
- apps/moodle-apps-azure/justfile
- apps/moodle-apps-azure/maintain-moodle.sh
- scripts/setup_moodle_webservice.php
- Generating web service token in Github Actions run and storing in key vault
- Adding support to setup_moodle_webservice.php to accept provided token
- Masking token in deployment output
- Creating background SSH session as close as possible to actual SSH session for more reliable deployments
> SWIP-584 Completing / testing web service integration

- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilitySocialWorkEnglandDropoutPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilityStatutoryWorkDropoutPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilityStatutoryWorkPageTests.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityStatutoryWork.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityStatutoryWorkDropout.cshtml
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityStatutoryWorkDropout.cshtml.cs
- apps/user-management/apps/frontend/Routing/EcfLinkGenerator.cs
> [SWIP592] Add statutory work dropout page

- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilityAgencyWorkerDropoutPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilityAgencyWorkerPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilityStatutoryWorkPageTests.cs
- apps/user-management/apps/frontend/Models/CreateAccountJourneyModel.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityAgencyWorker.cshtml
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityAgencyWorker.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityAgencyWorkerDropout.cshtml
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityAgencyWorkerDropout.cshtml.cs
- apps/user-management/apps/frontend/Routing/EcfLinkGenerator.cs
- apps/user-management/apps/frontend/Services/Journeys/CreateAccountJourneyService.cs
- apps/user-management/apps/frontend/Services/Journeys/Interfaces/ICreateAccountJourneyService.cs
- apps/user-management/apps/frontend/Validation/EligibilityAgencyWorkerValidator.cs
Video for flow uploaded to ticket
> [SWIP-580] Add agency worker eligibility question 

- .github/dependabot.yml
Added dependabot dependencies / security scanning config for:
- Github Actions
- Terraform
- Docker
- .NET
- NPM
Scheduled for early Monday each week, so will review any subsequent outputs next week. Also passes yaml validation but can't test easily.
> SWIP-202 Dependabot config

- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilityAgencyWorkerPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilityFundingAvailablePageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilityFundingNotAvailablePageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilityQualificationPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EligibilityStatutoryWorkPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/SelectUseCasePageTests.cs
- apps/user-management/apps/frontend/HttpClients/AuthService/Models/CreatePersonRequest.cs
- apps/user-management/apps/frontend/HttpClients/AuthService/Models/Person.cs
- apps/user-management/apps/frontend/Models/Account.cs
- apps/user-management/apps/frontend/Models/CreateAccountJourneyModel.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityFundingAvailable.cshtml
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityFundingAvailable.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityFundingNotAvailable.cshtml
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityFundingNotAvailable.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityQualification.cshtml
- apps/user-management/apps/frontend/Pages/ManageAccounts/EligibilityQualification.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/SelectUseCase.cshtml
- apps/user-management/apps/frontend/Pages/ManageAccounts/SelectUseCase.cshtml.cs
- apps/user-management/apps/frontend/Routing/EcfLinkGenerator.cs
- apps/user-management/apps/frontend/Services/AccountService.cs
- apps/user-management/apps/frontend/Services/Journeys/CreateAccountJourneyService.cs
- apps/user-management/apps/frontend/Services/Journeys/Interfaces/ICreateAccountJourneyService.cs
- apps/user-management/apps/frontend/Validation/EligibilityQualificationValidator.cs
https://github.com/user-attachments/assets/07b7b632-abdd-46e9-a366-848975562caa
> [SWIP-581] Add eligibility qualification page w/ funding pages

- .github/workflows/codeql.yml
- .github/workflows/trivy.yml
- apps/auth-service/Dfe.Sww.Ecf/Dockerfile
- apps/auth-service/Dfe.Sww.Ecf/entry-point.sh
- apps/auth-service/Dfe.Sww.Ecf/sshd_config
- apps/moodle-apps-azure/entry-point.sh
- apps/user-management/apps/frontend/Dockerfile-azure
- apps/user-management/apps/frontend/entry-point.sh
- Added CodeQL workflow
- Added Trivy workflow
- Fixed / clarified container user privileges and tested containers still work. We start with root, and de-escalate privileges to the appropriate user.
> SWIP-202 Setup CodeQL and Trivy - also fix / clarify container root permissions

- apps/user-management/apps/frontend.Test/UnitTests/Helpers/Builders/AccountBuilder.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/AddAccountDetailsPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/EditAccountDetailsPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Validators/AccountDetailsValidatorTests.cs
- apps/user-management/apps/frontend/Models/AccountDetails.cs
- apps/user-management/apps/frontend/Models/EditAccountJourneyModel.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/AddAccountDetails.cshtml
- apps/user-management/apps/frontend/Pages/ManageAccounts/AddAccountDetails.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/EditAccountDetails.cshtml.cs
- apps/user-management/apps/frontend/Validation/AccountDetailsValidator.cs
- apps/user-management/apps/frontend/Validation/Common/CommonValidators.cs
NOTE - Middle name and "Continue" button text are to be done in a different ticket. This is purely error messages for **blank/empty** inputs
> [SWIP-609] Add correct error messages for blank inputs for SWE workers

- .github/workflows/terraform.yaml
- terraform/auth-service.tf
- terraform/modules/environment-stack/alerting.tf
- terraform/modules/environment-stack/outputs.tf
- terraform/modules/environment-stack/variables.tf
- terraform/modules/web-app/alerting.tf
- terraform/modules/web-app/front-door-routes.tf
- terraform/modules/web-app/variables.tf
- terraform/modules/web-app/web-app.tf
- terraform/moodle-web-apps.tf
- terraform/proxy-service.tf
- terraform/stack.tf
- terraform/user-management.tf
- terraform/variables.tf
Added health checks for:
- Moodle site
- Moodle cron service
- proxy service 
- user management 
- auth service
Azure sends alerts to new Slack non-prod support channel for failing health checks
> SWIP-522 Implement health checks for web apps

- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/ConfirmAccountDetailsPageTests.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/ConfirmAccountDetails.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/Index.cshtml
> [SWIP-618] Update add new user banner

- .github/workflows/build-and-optionally-deploy-auth-service.yml
- .github/workflows/build-and-optionally-deploy-moodle-apps.yml
- .github/workflows/build-and-optionally-deploy-proxy-service.yml
- .github/workflows/build-and-optionally-deploy-user-management.yml
- .github/workflows/deploy-auth-service.yml
- .github/workflows/deploy-moodle-app.yml
- .github/workflows/deploy-user-management.yml
- .github/workflows/terraform.yaml
- terraform/envs/d02/env.tfvars
- terraform/envs/d03/env.tfvars
- Added new Terraform environment  - d03
- Added d03 to build / deploy workflows 
- Added stand-along user management deploy workflow
Note: new user management workflow will be tested after merge to main as you can't test a new workflow from the Github Actions UI
> SWIP 696 New user research env

- apps/user-management/apps/frontend/Pages/Shared/_AuthenticatedHeader.cshtml
- apps/user-management/apps/frontend/Pages/Shared/_Header.cshtml
Authenticated Header 
Un-athenticated Header
> [SWIP-620] Rename service name throughout app

- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/ConfirmAccountDetailsPageTests.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/Index.cshtml
dont display "first" on 1st page, don't display "next" on last page
Don't display pagination on views with only 1 page 
fix unit test also
First Page
Last Page
Only 1 page
> [SWIP-625] Update table pagination

- apps/user-management/apps/frontend.Test/UnitTests/Helpers/Builders/AccountBuilder.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/IndexPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/SocialWorkerRegistration/SelectEthnicGroupPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/SocialWorkerRegistration/SelectSexAndGenderIdentityPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/RegisterSocialWorkerJourneyServiceTests/GetEthnicGroupShould.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/RegisterSocialWorkerJourneyServiceTests/GetOtherGenderIdentityShould.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/RegisterSocialWorkerJourneyServiceTests/SetEthnicGroupShould.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/RegisterSocialWorkerJourneyServiceTests/SetOtherGenderIdentityShould.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/RegisterSocialWorkerJourneyServiceTests/SetUserSexShould.cs
- apps/user-management/apps/frontend/Models/Account.cs
- apps/user-management/apps/frontend/Models/EthnicGroup.cs
- apps/user-management/apps/frontend/Models/RegisterSocialWorkerJourneyModel.cs
- apps/user-management/apps/frontend/Pages/SocialWorkerRegistration/SelectEthnicGroup.cshtml
- apps/user-management/apps/frontend/Pages/SocialWorkerRegistration/SelectEthnicGroup.cshtml.cs
- apps/user-management/apps/frontend/Routing/EcfLinkGenerator.cs
- apps/user-management/apps/frontend/Services/Journeys/Interfaces/IRegisterSocialWorkerJourneyService.cs
- apps/user-management/apps/frontend/Services/Journeys/RegisterSocialWorkerJourneyService.cs
- apps/user-management/apps/frontend/Validation/SelectEthnicGroupValidator.cs
Images of the UI available on the ticket
> [SWIP-587] Add main ethnic group page

- apps/user-management/apps/frontend.Test/UnitTests/Helpers/Builders/ClaimsPrincipalBuilder.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/IndexTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/WelcomeTests.cs
- apps/user-management/apps/frontend/Pages/Index.cshtml
- apps/user-management/apps/frontend/Pages/Index.cshtml.cs
- apps/user-management/apps/frontend/Pages/Welcome.cshtml
- apps/user-management/apps/frontend/Pages/Welcome.cshtml.cs
- apps/user-management/apps/frontend/Routing/EcfLinkGenerator.cs
- Refactor welcome page into a separate page away from index logic
- Add welcome page content for social worker
- Keep existing content for all other roles for now, to be refactored in future tickets
> SWIP-636 - Social worker welcome page

- .github/workflows/build-and-optionally-deploy-auth-service.yml
- .github/workflows/build-and-optionally-deploy-moodle-apps.yml
- .github/workflows/build-and-optionally-deploy-proxy-service.yml
- .github/workflows/build-and-optionally-deploy-user-management.yml
- .github/workflows/deploy-auth-service.yml
- .github/workflows/deploy-moodle-app.yml
- .github/workflows/deploy-proxy-service.yml
- .github/workflows/deploy-user-management.yml
- .github/workflows/terraform.yaml
- terraform/envs/d04/env.tfvars
Create new d04 temp dev environment
> SWIP-796 New temp dev environment

- apps/user-management/.editorconfig
- apps/user-management/apps/frontend.Test/UnitTests/Helpers/Builders/AccountBuilder.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/SocialWorkerRegistration/SelectHighestQualificationPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/SocialWorkerRegistration/SelectSocialWorkQualificationEndYearPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/RegisterSocialWorkerJourneyServiceTests/GetSocialWorkQualificationEndYearShould.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/RegisterSocialWorkerJourneyServiceTests/SetSocialWorkQualificationEndYearShould.cs
- apps/user-management/apps/frontend/Models/Account.cs
- apps/user-management/apps/frontend/Models/RegisterSocialWorker/RegisterSocialWorkerJourneyModel.cs
- apps/user-management/apps/frontend/Pages/SocialWorkerRegistration/SelectSocialWorkQualificationEndYear.cshtml
- apps/user-management/apps/frontend/Pages/SocialWorkerRegistration/SelectSocialWorkQualificationEndYear.cshtml.cs
- apps/user-management/apps/frontend/Routing/EcfLinkGenerator.cs
- apps/user-management/apps/frontend/Services/Journeys/Interfaces/IRegisterSocialWorkerJourneyService.cs
- apps/user-management/apps/frontend/Services/Journeys/RegisterSocialWorkerJourneyService.cs
- apps/user-management/apps/frontend/Validation/RegisterSocialWorker/SocialWorkQualificationEndYearValidator.cs
Images of the UI are available on the PR
> [SWIP-604] Add social work qualification end year page

- docs/devops/Future DevOps Work.md
Document future DevOps work / considerations
> SWIP 810 Document future DevOps work / considerations

- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/ViewAccountDetailsPageTests.cs
- apps/user-management/apps/frontend/Models/Account.cs
- apps/user-management/apps/frontend/Models/RegisterSocialWorker/RegisterSocialWorkerJourneyModel.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/ViewAccountDetails.cshtml.cs
Changes for [SWIP-630](https://dfedigital.atlassian.net/browse/SWIP-630) including:
- temp data for banner in view details page
- unit test update for notification banner temp data
- update to account full name property to include middle name
[SWIP-630]: https://dfedigital.atlassian.net/browse/SWIP-630?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SWIP-630 invite resend success banner

- apps/user-management/apps/frontend.Test/UnitTests/Helpers/Fakers/AccountDetailsFaker.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/ConfirmAccountDetailsPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/SelectAccountTypePageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/SelectUseCasePageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/CreateAccountJourneyServiceTests/GetAccountChangeLinksShould.cs
- apps/user-management/apps/frontend/Models/AccountChangeLinks.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/ConfirmAccountDetails.cshtml
- apps/user-management/apps/frontend/Pages/ManageAccounts/ConfirmAccountDetails.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/SelectAccountType.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/SelectUseCase.cshtml.cs
- apps/user-management/apps/frontend/Routing/EcfLinkGenerator.cs
- apps/user-management/apps/frontend/Services/Journeys/CreateAccountJourneyService.cs
Changes for [SWIP-662](https://dfedigital.atlassian.net.mcas.ms/browse/SWIP-662) including:
- addition of account type row to the check details page 
- logic changes to handle user details being changed and the appropriate flow between pages
- unit tests for the changes and some improvements to unit tests coverage for the check details page page
Video on the Jira ticket.
[SWIP-662]: https://dfedigital.atlassian.net/browse/SWIP-662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SWIP-662 check coordinator details

- docs/devops/Component Deployment.md
- New document for component deployment
> SWIP-812 Document component deployment

- docs/devops/Current Environments.md
- docs/devops/Github and Terraform Variables.md
- docs/devops/System Runbook.md
- Add runbook doc
- Add current environments doc
- Minor changes to variables doc
> SWIP-813 Runbook, environments and minor variables changes

- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageAccounts/ConfirmAccountDetailsPageTests.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/ConfirmAccountDetails.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageAccounts/ViewAccountDetails.cshtml
> SWIP-817 - Show success banner on user details update

- apps/auth-service/Dfe.Sww.Ecf/src/Dfe.Sww.Ecf.AuthorizeAccess/Controllers/KeysController.cs
- terraform/envs/d02/env.tfvars
- terraform/envs/d03/env.tfvars
- terraform/envs/d04/env.tfvars
Enable Moodle persistent file sync for d02, d03, d04
> Swip 783 Enable Moodle persistent file sync for d02, d03, d04

- apps/user-management/apps/frontend.Test/UnitTests/Helpers/Builders/ClaimsPrincipalBuilder.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/DashboardTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/IndexTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/SignInTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/WelcomeTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/TagHelpers/GovUkCardsTagHelperTests.cs
- apps/user-management/apps/frontend/Models/ManageOrganisations/CardItem.cs
- apps/user-management/apps/frontend/Models/ManageOrganisations/CardLink.cs
- apps/user-management/apps/frontend/Pages/Dashboard.cshtml
- apps/user-management/apps/frontend/Pages/Dashboard.cshtml.cs
- apps/user-management/apps/frontend/Pages/Shared/_AuthenticatedHeader.cshtml
- apps/user-management/apps/frontend/Pages/Shared/_Header.cshtml
- apps/user-management/apps/frontend/Pages/SignIn.cshtml.cs
- apps/user-management/apps/frontend/Pages/Welcome.cshtml.cs
- apps/user-management/apps/frontend/Routing/EcfLinkGenerator.cs
- apps/user-management/apps/frontend/TagHelpers/GovUkCardsTagHelper.cs
- apps/user-management/apps/frontend/wwwroot/css/cards.css
- apps/user-management/apps/frontend/wwwroot/css/site.css
Changes for [SWIP-877](https://dfedigital.atlassian.net.mcas.ms/browse/SWIP-877):
- dashboard page
- adaptation of Ruby [cards component](https://components.publishing.service.gov.uk/component-guide/cards)
- unit tests
- changes to use RoleType class instead of AccountType when referring to role of authenticated user
[SWIP-877]: https://dfedigital.atlassian.net/browse/SWIP-877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SWIP-877 Dashboard page and cards component

- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageOrganisations/ConfirmOrganisationDetailsPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageOrganisations/EnterLocalAuthorityCodePageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/CreateOrganisationJourneyServiceTests/GetOrganisationShould.cs
- apps/user-management/apps/frontend/Models/ManageOrganisation/Organisation.cs
- apps/user-management/apps/frontend/Models/ManageOrganisation/OrganisationType.cs
- apps/user-management/apps/frontend/Pages/ManageOrganisations/ConfirmOrganisationDetails.cshtml
- apps/user-management/apps/frontend/Pages/ManageOrganisations/ConfirmOrganisationDetails.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageOrganisations/EnterLocalAuthorityCode.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageOrganisations/Index.cshtml
- apps/user-management/apps/frontend/Routing/EcfLinkGenerator.cs
- apps/user-management/apps/frontend/Services/Journeys/CreateOrganisationJourneyService.cs
- apps/user-management/apps/frontend/Services/Journeys/Interfaces/ICreateOrganisationJourneyService.cs
Video/images of the UI available on the ticket
> [SWIP-882] Confirm org details

- apps/user-management/apps/frontend.Test/UnitTests/Helpers/Builders/OrganisationBuilder.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageOrganisations/EditPrimaryCoordinatorChangeTypePageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageOrganisations/EditPrimaryCoordinatorPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageOrganisations/OrganisationDetailsPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/EditOrganisationJourneyServiceTests/EditOrganisationJourneyServiceTestBase.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/EditOrganisationJourneyServiceTests/GetOrganisationShould.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/EditOrganisationJourneyServiceTests/GetPrimaryCoordinatorAccountShould.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/EditOrganisationJourneyServiceTests/GetPrimaryCoordinatorChangeTypeShould.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/EditOrganisationJourneyServiceTests/ResetEditOrganisationJourneyModelShould.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/EditOrganisationJourneyServiceTests/SetOrganisationShould.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/EditOrganisationJourneyServiceTests/SetPrimaryCoordinatorAccountDetailsShould.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/EditOrganisationJourneyServiceTests/SetPrimaryCoordinatorChangeType.cs
- apps/user-management/apps/frontend/Models/ManageOrganisation/EditOrganisationJourneyModel.cs
- apps/user-management/apps/frontend/Pages/ManageOrganisations/EditPrimaryCoordinator.cshtml
- apps/user-management/apps/frontend/Pages/ManageOrganisations/EditPrimaryCoordinator.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageOrganisations/EditPrimaryCoordinatorChangeType.cshtml
- apps/user-management/apps/frontend/Pages/ManageOrganisations/EditPrimaryCoordinatorChangeType.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageOrganisations/OrganisationDetails.cshtml
- apps/user-management/apps/frontend/Pages/ManageOrganisations/OrganisationDetails.cshtml.cs
- apps/user-management/apps/frontend/Routing/ManageOrganisationLinks.cs
- apps/user-management/apps/frontend/Services/Journeys/EditOrganisationJourneyService.cs
- apps/user-management/apps/frontend/Services/Journeys/Interfaces/IEditOrganisationJourneyService.cs
video of the flow available on the ticket
> [SWIP-891] Add editprimarycoordinator page

- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageOrganisations/CheckYourAnswersPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageOrganisations/EditPrimaryCoordinatorPageTests.cs
- apps/user-management/apps/frontend.Test/UnitTests/Services/OrganisationServiceTests/CreateShould.cs
- apps/user-management/apps/frontend/Pages/ManageOrganisations/CheckYourAnswers.cshtml
- apps/user-management/apps/frontend/Pages/ManageOrganisations/CheckYourAnswers.cshtml.cs
- apps/user-management/apps/frontend/Pages/ManageOrganisations/EditPrimaryCoordinator.cshtml.cs
- apps/user-management/apps/frontend/Routing/ManageOrganisationLinks.cs
video of the UI/flow available on the ticket
> [SWIP-892] Add edit functionality to org check answers page

- apps/user-management/apps/frontend.Test/UnitTests/Pages/ManageOrganisations/CheckYourAnswersPageTests.cs
- apps/user-management/apps/frontend/Pages/ManageOrganisations/CheckYourAnswers.cshtml.cs
> [SWIP-893] Remove message from edit primary coordinator banner

- apps/moodle-ddev/.ddev/commands/web/install-oidc-plugin
- apps/user-management/apps/frontend.Test/UnitTests/Services/JourneyTests/CreateAccountJourneyServiceTests/CreateAccountJourneyServiceTestBase.cs
- apps/user-management/apps/frontend/Models/SocialWorkEnglandRecord.cs
- apps/user-management/apps/notification-service-test/FunctionalTests/Builders/Http/HttpRequestClient.cs
- apps/user-management/apps/notification-service-test/UnitTests/Validators/NotificationRequestTests/ValidateShould.cs
Changes for code scanning notes:
- [#383](https://github.com/DFE-Digital/social-work-induction-programme-digital-service/security/code-scanning/383)
- [#98](https://github.com/DFE-Digital/social-work-induction-programme-digital-service/security/code-scanning/98)
- [#97](https://github.com/DFE-Digital/social-work-induction-programme-digital-service/security/code-scanning/97)
- [#69](https://github.com/DFE-Digital/social-work-induction-programme-digital-service/security/code-scanning/69)
Also including a fix for the moodle oidc plugin install script.
> SWIP-953 Fix code scanning notes

- apps/user-management/apps/frontend/Pages/LoggedOut.cshtml
> [SWIP-1009] Update sign out page content

- apps/user-management/apps/frontend/Pages/ManageAccounts/ConfirmAccountDetails.cshtml.cs
> SWIP-1008 - fix: update Programme end/start date description text
